name: Build ARM64 Binary with Poetry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up QEMU for ARM64 emulation
      - name: Enable QEMU for ARM64 Emulation
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      # Build ARM64 binary using Docker
      - name: Build Binary with Poetry
        run: |
          # Use a Debian-based image and install dependencies
          docker run --rm --platform linux/arm64/v8 -v $PWD:/workspace -w /workspace debian:buster bash -c "
            # Install required system dependencies
            apt-get update && apt-get install -y \
              python3.11 python3.11-dev python3.11-distutils python3-pip \
              build-essential libssl-dev libffi-dev && \
            
            # Install Poetry
            curl -sSL https://install.python-poetry.org | python3.11 && \
            export PATH=/root/.local/bin:\$PATH && \
            
            # Configure Poetry and install dependencies
            poetry self add poetry-pyinstaller-plugin==1.1.13 && \
            poetry install && \
            
            # Build the binary using Poetry
            poetry build
          "

      # Upload the generated binary as an artifact
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: poetry-build
          path: dist/*
