name: Build Binary

on:
  push:
    branches:
      - main  # Adjust based on the branches you want to trigger builds
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04  # Specify the Ubuntu version
    architecture: aarch64  # Specify the architecture

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Choose the Python version you need

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Binary
        run: |
          pyinstaller --onefile main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: dist/main  # Path to the generated binary
