name: Build ARM64 Binary with Poetry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Build ARM64 binary using Docker with Debian Buster
      - name: Build Binary with Poetry
        run: |
          docker run --rm --platform linux/arm64/v8 -v $PWD:/workspace -w /workspace debian:buster bash -c "
            # Update package lists and install dependencies
            apt-get update && apt-get install -y \
              software-properties-common build-essential libssl-dev libffi-dev curl && \
            
            # Add the deadsnakes PPA for Python 3.11
            add-apt-repository ppa:deadsnakes/ppa && \
            apt-get update && \
            
            # Install Python 3.11 and necessary packages
            apt-get install -y python3.11 python3.11-dev python3.11-distutils python3-pip && \
            
            # Install Poetry
            curl -sSL https://install.python-poetry.org | python3.11 && \
            export PATH=/root/.local/bin:\$PATH && \
            
            # Install the poetry-pyinstaller-plugin
            poetry self add poetry-pyinstaller-plugin==1.1.13 && \
            
            # Install the dependencies using Poetry
            poetry install && \
            
            # Build the binary using Poetry
            poetry build
          "

      # Upload the generated binary as an artifact
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: poetry-build
          path: dist/*
