name: Build ARM64 Binary with Poetry

on:
  push:
    branches:
      - dev1
  pull_request:
    branches:
      - dev1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Build Binary with Poetry
      - name: Build on aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          install: |
            apt update -y
            apt install -y build-essential zlib1g-dev \
            libssl-dev libreadline-dev libffi-dev wget libbz2-dev
            wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
            tar -xvzf Python-3.11.0.tgz
            cd Python-3.11.0
            ./configure --enable-optimizations --prefix=/usr/local --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
            make -j$(nproc)
            make altinstall

          run: |
            ls usr/local/lib*
      # Upload the generated binary as an artifact
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: poetry-build
          path: dist/*

          