name: Build ARM64 Binary with PyInstaller

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 as the base runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the code in the repo

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker buildx for ARM64

      - name: Build using ARM64 Docker Image
        run: |
          docker run --rm --platform linux/arm64/v8 -v $PWD:/workspace -w /workspace python:3.10-slim bash -c "
            apt-get update && apt-get install -y python3-dev python3-pip build-essential libssl-dev libffi-dev
            pip install pyinstaller
            pyinstaller --onefile main.py  # Build the binary using PyInstaller
          "

      - name: Upload Artifact
        uses: actions/upload-artifact@v3  # Upload the generated binary as an artifact
        with:
          name: binary
          path: dist/main  # Path to the generated binary inside the dist directory
